# Generated by kpex 0.3.7
crashbackups stop
drc off
gds read /foss/designs/gds/Aymen/ramp_generator.gds
load ramp_generator
select top cell
flatten ramp_generator_flat
load ramp_generator_flat
cellname delete ramp_generator -noprompt
cellname rename ramp_generator_flat ramp_generator
select top cell
extract path /foss/designs/gds/Aymen/output/ramp_generator__ramp_generator/magic_RC
extract all
ext2sim labels on
ext2sim -p /foss/designs/gds/Aymen/output/ramp_generator__ramp_generator/magic_RC
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/gds/Aymen/output/ramp_generator__ramp_generator/magic_RC -o /foss/designs/gds/Aymen/output/ramp_generator__ramp_generator/magic_RC/ramp_generator.pex.spice
quit -noprompt
